name: 'firestore-backup-action'
description: 'Github action to backup Firebase Firestore to Google cloud'
inputs:
  project-id:
    description: 'The project id'
    required: true
  bucket-path:
    description: 'The bucket path e.g gs://my-bucket or gs://my-bucket/my-folder'
    required: true
  service-account-key:
    description: 'The service account key'
    required: true
  collection-ids:
    description: 'Optional - a comma separated list of collection ids to backup'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v3'
    - name: 'Login to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ inputs.service-account-key }}'
        export_environment_variables: true
        create_credentials_file: true
    - name: 'Setup Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Display Google cloud info'
      shell: 'bash'
      run: 'gcloud info'
    - name: 'Set the project'
      shell: 'bash'
      run: 'gcloud config set project "${{ inputs.project-id }}"'
    - name: 'Run generic export'
      shell: 'bash'
      if: ${{ inputs.collection-ids == '' }}
      run: 'gcloud firestore export "${{ inputs.bucket-path }}"'
    - name: 'Run specific export'
      shell: 'bash'
      if: ${{ inputs.collection-ids != '' }}
      run: 'gcloud firestore export "${{ inputs.bucket-path }}" --collection-ids="${{ inputs.collection-ids }}"'
